# Generated by Django 6.0.5 on 2026-05-26 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['grupo', 'user__last_name']},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['semestre', 'carrera', 'grupo_letra']},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['clave']},
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], default='Matutino', max_length=20),
        ),
        migrations.AddField(
            model_name='materia',
            name='creditos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='carrera',
            field=models.CharField(choices=[('LOGISTICA', 'Logística'), ('CIENCIA_DATOS', 'Ciencia de Datos'), ('ANIMACION_DIGITAL', 'Animación Digital')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('semestre', 'grupo_letra', 'carrera', 'turno')},
        ),
    ]
