# Generated by Django 6.0.5 on 2026-06-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_alumno_options_alter_grupo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='carrera',
            field=models.CharField(blank=True, choices=[('LOGISTICA', 'Logística'), ('CIENCIA_DATOS', 'Ciencia de Datos'), ('ANIMACION_DIGITAL', 'Animación Digital')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
