// ── Catálogo Completo para Bento Grid (MomentsGallery) ────────────────────────
export const bentoGalleryMoments = [
  // Vida en el Campus y Actividades Generales
  { src: alumA, caption: "Momentos de aprendizaje en el campus", alt: "Estudiantes en actividad" },
  { src: alumB, caption: "Vida estudiantil CECyTEM", alt: "Actividad de alumnos" },
  { src: dataImg, caption: "Campus CECyTEM Toluca II", alt: "Instalaciones del plantel" },
  { src: lab2, caption: "Espacios académicos", alt: "Área del campus" },
  { src: lab3, caption: "Ambiente de trabajo colaborativo", alt: "Estudiantes colaborando" },
  { src: cecytem5img, caption: "Desarrollo de habilidades técnicas", alt: "Actividad técnica" },
  { src: cecytem7, caption: "Formación integral del estudiante", alt: "Experiencia educativa" },
  { src: cecytem8, caption: "Actividades estudiantiles", alt: "Actividades" },
  { src: actividades12, caption: "Actividades extracurriculares", alt: "Actividades estudiantiles" },
  
  // Bloque: Deportes Toluca (Canchas, Equipos, Torneos)
  { src: deportes2, caption: "Deporte en CECyTEM Toluca", alt: "Deportes Toluca" },
  { src: deportes21, caption: "Actividad deportiva institucional", alt: "Deportes Toluca 2.1" },
  { src: deportes22, caption: "Formación física y salud", alt: "Deportes Toluca 2.2" },
  { src: deportes23, caption: "Torneo de fútbol interno", alt: "Deportes Toluca 2.3" },
  { src: deportes24, caption: "Competencia deportiva estudiantil", alt: "Deportes Toluca 2.4" },
  { src: deportes25, caption: "Valores de trabajo en equipo", alt: "Deportes Toluca 2.5" },
  { src: deportes26, caption: "Encuentros deportivos locales", alt: "Deportes Toluca 2.6" },
  { src: deportes27, caption: "Equipo representativo del plantel", alt: "Deportes Toluca 2.7" },
  { src: deportes28, caption: "Identidad y disciplina deportiva", alt: "Deportes Toluca 2.8" },
  { src: deportes29, caption: "Convivencia inter-escolar", alt: "Deportes Toluca 2.9" },
  { src: deportes31, caption: "Torneo estudiantil de fútbol", alt: "Deportes Toluca 3.1" },
  { src: deportes32, caption: "Desarrollo deportivo integral", alt: "Deportes Toluca 3.2" },
  { src: deportes33, caption: "Sana competencia en el plantel", alt: "Deportes Toluca 3.3" },
  { src: deportes34, caption: "Talleres deportivos de fin de semana", alt: "Deportes Toluca 3.4" },
  { src: deportes35, caption: "Selección de atletas CECyTEM", alt: "Deportes Toluca 3.5" },
  { src: deportes3, caption: "Deporte, salud y convivencia", alt: "Deportes Toluca 3" },

  // Bloque: Secuencias Fotográficas Campus Toluca II
  { src: toluca2, caption: "Instalaciones del Plantel Toluca II", alt: "Toluca 2" },
  { src: toluca21, caption: "Acceso y áreas comunes", alt: "Toluca 2.1" },
  { src: toluca22, caption: "Desarrollo de infraestructura", alt: "Toluca 2.2" },
  { src: toluca27, caption: "Vida estudiantil en Totoltepec", alt: "Toluca 2.7" },
  { src: toluca28, caption: "Comunidad escolar unida", alt: "Toluca 2.8" },
  { src: toluca29, caption: "Talleres y laboratorios técnicos", alt: "Toluca 2.9" },
  { src: toluca31, caption: "Comunidad académica activa", alt: "Toluca 3.1" },
  { src: toluca32, caption: "Eventos cívicos y culturales", alt: "Toluca 3.2" },
  { src: toluca33, caption: "Identidad institucional CECyTEM", alt: "Toluca 3.3" },
  { src: toluca34, caption: "Talleres de Ciencia de Datos", alt: "Toluca 3.4" },
  { src: toluca35, caption: "Formación para el futuro digital", alt: "Toluca 3.5" },
  { src: toluca3, caption: "Infraestructura en evolución constante", alt: "Toluca 3" },
  { src: toluca41, caption: "Formación académica de excelencia", alt: "Toluca 4.1" },
  { src: toluca42, caption: "Proyectos integradores de semestre", alt: "Toluca 4.2" },
  { src: toluca43, caption: "Habilidades técnicas aplicadas", alt: "Toluca 4.3" },
  { src: toluca44, caption: "Prácticas profesionales internas", alt: "Toluca 4.4" },
  { src: toluca45, caption: "Docentes especializados guiando proyectos", alt: "Toluca 4.5" },
  { src: toluca46, caption: "Proyecto estudiantil de bases de datos", alt: "Toluca 4.6" },
  { src: toluca47, caption: "Soluciones de logística empresarial", alt: "Toluca 4.7" },
  { src: toluca48, caption: "Simulación de cadenas de suministro", alt: "Toluca 4.8" },
  { src: toluca49, caption: "Presentaciones de fin de cursos", alt: "Toluca 4.9" },
  { src: toluca4, caption: "Evaluaciones técnicas profesionales", alt: "Toluca 4" },
  { src: toluca51, caption: "Experiencia educativa bivalente", alt: "Toluca 5.1" },
  { src: toluca52, caption: "Tutorías y acompañamiento continuo", alt: "Toluca 5.2" },
  { src: toluca53, caption: "Orientación educativa integral", alt: "Toluca 5.3" },
  { src: toluca54, caption: "Ambiente inclusivo y seguro", alt: "Toluca 5.4" },
  { src: toluca55, caption: "Espacios de crecimiento personal", alt: "Toluca 5.5" },
  { src: toluca56, caption: "Innovación y tecnología en el aula", alt: "Toluca 5.6" },
  { src: toluca57, caption: "Metodologías ágiles de estudio", alt: "Toluca 5.7" },
  { src: toluca58, caption: "Estadística y minería de datos", alt: "Toluca 5.8" },
  { src: toluca59, caption: "Preparación académica pre-universitaria", alt: "Toluca 5.9" },
  { src: toluca5, caption: "Orgullo CECyTEM Estado de México", alt: "Toluca 5" },
  { src: toluca61, caption: "Entorno del campus Toluca II", alt: "Toluca 6.1" },
  { src: toluca62, caption: "Vinculación con el sector productivo", alt: "Toluca 6.2" },
  { src: toluca63, caption: "Competencias para la economía digital", alt: "Toluca 6.3" },
  { src: toluca64, caption: "Egresados con perfil competitivo", alt: "Toluca 6.4" },
  { src: toluca6, caption: "Tu futuro profesional inicia aquí", alt: "Toluca 6" }
];