# Generated by Django 6.0.5 on 2026-08-13 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_alter_asignaciondocente_docente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputadoraSala',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento')], default='LIBRE', max_length=20)),
                ('alumno', models.CharField(blank=True, max_length=150, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAccesoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=150)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('hora_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('computadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='seguimiento.computadorasala')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
